### ISSUE TITLE
Enhancement request for data binding

### ISSUE THREAD

**Issue by DBojsen** [microsoft/powerbi-report-authoring#1]
Hi

I'm working on a rather dynamic embedding solution, and have 2 requests:
1) removeDataField shouldn't auto refresh the report - I want to remove multiple elements from the Row collection of a matrix visual, and only when I'm done, I would like to manually call the refresh method.

2) addDataField needs to take an index position or something similar where you wan't it to be inserted.  It is no good, that it is always added to the end of the array.

Keep up the good work.

BR David

**Comment by ali-hamud** [comment]
Thanks @DBojsen for the feedback

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. We closed the issue because it's old.
