### ISSUE TITLE
How to get/set actionButton visual properties

### ISSUE THREAD

**Issue by barryschulz** [microsoft/powerbi-report-authoring#17]
I am trying to set the text of an actionButton using the following code, but receive an "Unsupported property" exception. How do you set the actionButton's text property?

https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/visual-properties#selecting-the-format-object-and-property

"powerbi-client": "2.18.7",
"powerbi-report-authoring": "1.1.3",
`
const buttonText = await visual.getProperty({ objectName: 'text', propertyName: 'text' });
`
<pre>
{
	"name": "f2577fc59e2d790abb85",
	 singleVisual": {
		"visualType": "actionButton",
		"objects": {
			text": [
				{
					"properties": {
						"show": {
							"expr": {
								"Literal": {
									"Value": "true"
								}
							}
						}
					}
				},
				{
					"properties": {
						"text": {
							"expr": {
								"Literal": {
									"Value": "'Hello World'"
								}
							}
						},
						"fontFamily": {
							"expr": {
								"Literal": {
									"Value": "'''Segoe UI Semibold'', wf_segoe-ui_semibold, helvetica, arial, sans-serif'"
								}
							}
						},
						"fontSize": {
							"expr": {
								"Literal": {
									"Value": "10D"
								}
							}
						}
					},
					"selector": {
						"id": "default"
					}
				}
			],
	},
	"parentGroupName": "20312eb3ab5ac0044dfa"
}
</pre>

**Comment by v-MadhavC** [comment]
Setting the text property of the action button is not available. You can only retrieve, set, or reset visual properties that are listed in the [documentation](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/visual-properties#available-properties-for-out-of-the-box-visuals).
