### ISSUE TITLE
[Enhancement Request] More options for adding to visuals/datapoints

### ISSUE THREAD

**Issue by jshinevar** [microsoft/powerbi-report-authoring#4]
Currently, when using the library, I am able to do minor items, but, it would be great if there were more options.  For example, I would like to highlight a single data point by either changing isn't color or some attribute to bring attention to a specific data point.  It would also be good if I could inject some HTML and/or an icon into the title of a visual.

I have built a discussion system for a project using power bi embedded and I would like to directly highlight or identify where comments are placed in the embedded report.  There is not an option to do this programmatically from JavaScript.

**Comment by jshinevar** [comment]
Or, if it was possible to append text to a title that is bold while the rest of the title is not.  That would be useful.  Right now, I can only update the entire text and the entire format.

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. We closed the issue because it's old.
