### ISSUE TITLE
addDatafield based on dataSelected event handler

### ISSUE THREAD

**Issue by MHeybroek** [microsoft/powerbi-report-authoring#7]
For one project where we use the powerbi API we like to mimic a drill down capability where you can click on a bar for a certain month and that the visual will rerender with all the days for that specific month. We approach this feature by using a combination of the dataselected eventhandler method which triggers the setFilter method with that particular month as a filter. 
We then remove the datafield for the month and add the datafield for days.  

However, the problem with this approach is that when you select a certain month the bar for that month gets highlighted and all the newly added day bars are darkened. You subsequently have to click on the visual to make the bars light up again. The only option we found so far is to clone the visual, but than we can't see a tooltip anymore and lose some features. 

Is there a way to stop the highlighting of the bars or that removedatafield will reset the highlighting?

**Comment by ayeshurun** [comment]
Thank you for reporting this issue. We closed the issue because it's old.
