### ISSUE TITLE
AddDataField missing functionality - "Show items with no data"

### ISSUE THREAD

**Issue by gsimon1** [microsoft/powerbi-report-authoring#9]
Hello PowerBI guys!,

PowerBI - Desktop has the ability to add: "**Show items with no data**" to certain measures.

![image](https://user-images.githubusercontent.com/72401733/96186232-208a7800-0f09-11eb-9e10-933d4493cbda.png)
giving a result like this:

![image](https://user-images.githubusercontent.com/72401733/96186547-955db200-0f09-11eb-8f72-719809f2f662.png)

However, when using **powerbi-report-authoring** to set the "Category" (Axis) with the same measure(**MonthYear**) constructed like this:

```
const newPrimaryDataField: models.IColumnTarget = {
                $schema: 'http://powerbi.com/product/schema#column',
                column: 'MonthYear',
                table: Table_name
            };

//  Apply new data field
visual.addDataField('Category', newPrimaryDataField);
```

the end result is a chart with only items with data:

![image](https://user-images.githubusercontent.com/72401733/96186646-bf16d900-0f09-11eb-9d6d-ddf3378df7ea.png)

So the main question here is the following:

Is there a way to replicate the "**Show items with no data**" functionality from **PowerBI-Desktop** into the structure of the **measure** created with **PowerBI-report-authoring** so that the output is the same as in **PowerBI-Desktop**?

Thank you.

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is a feature request, please add it in the following link where we can collect votes: https://ideas.fabric.microsoft.com/ . If the feature is already there, you can add a vote.
